# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
