# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20160204_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserRegistrationInfo',
        ),
    ]
