# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160204_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date')),
                ('activation_code', models.CharField(default=None, max_length=100)),
                ('activation_Date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='validation date')),
            ],
        ),
        migrations.RemoveField(
            model_name='userregistrationinfo',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='userregistrationinfo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userregistrationinfo',
            name='activation_Date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='validation date'),
        ),
        migrations.AlterField(
            model_name='userregistrationinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='registration date'),
        ),
    ]
