# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20160204_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationinfo',
            old_name='activation_Date',
            new_name='activation_date',
        ),
    ]
