# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20160204_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreregistration',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
