# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20160204_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreRegistration',
        ),
        migrations.AddField(
            model_name='userregistrationinfo',
            name='activation_code',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
